In [1]:
import torch

In [14]:
x = torch.empty(5, 3)
print(x)

x = torch.rand(5, 3)
print(x)

x = torch.zeros(5, 3, dtype=torch.long)
print(x)

x = torch.tensor([5.5, 3])
print(x)

x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)
print(x.size())

tensor([[0.0000, 2.0000, 0.0000],
        [2.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])
tensor([[0.9811, 0.9543, 0.9813],
        [0.8671, 0.9784, 0.7246],
        [0.4406, 0.5418, 0.2236],
        [0.5895, 0.2983, 0.4081],
        [0.9547, 0.1046, 0.6195]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.2007, -0.2553, -0.6381],
        [ 1.1876, -1.0125,  1.3460],
        [ 1.7353, -0.1640,  0.2873],
        [ 0.9033,  1.3169,  0.8794],
        [ 0.2787,  0.6975, -0.0044]])
torch.Size([5, 3])


In [16]:
y = torch.rand(5, 3)
print(x + y)
print(torch.add(x, y))

tensor([[-0.1918,  0.5472, -0.5086],
        [ 1.6827, -0.8488,  1.5735],
        [ 1.8569, -0.1048,  0.8592],
        [ 1.3153,  2.2472,  1.7646],
        [ 1.2612,  1.5839,  0.9377]])
tensor([[-0.1918,  0.5472, -0.5086],
        [ 1.6827, -0.8488,  1.5735],
        [ 1.8569, -0.1048,  0.8592],
        [ 1.3153,  2.2472,  1.7646],
        [ 1.2612,  1.5839,  0.9377]])


In [19]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

y.add_(x)
print(y)

print(x[:, 1])

tensor([[-0.3925,  0.2919, -1.1467],
        [ 2.8702, -1.8613,  2.9195],
        [ 3.5922, -0.2688,  1.1465],
        [ 2.2186,  3.5642,  2.6440],
        [ 1.5399,  2.2814,  0.9332]])
tensor([[-0.3925,  0.2919, -1.1467],
        [ 2.8702, -1.8613,  2.9195],
        [ 3.5922, -0.2688,  1.1465],
        [ 2.2186,  3.5642,  2.6440],
        [ 1.5399,  2.2814,  0.9332]])
tensor([-0.2553, -1.0125, -0.1640,  1.3169,  0.6975])


In [21]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x)
print(y)
print(z)
print(x.size(), y.size(), z.size())

tensor([[ 0.1579, -0.0260, -0.9140,  0.2181],
        [-0.6974, -0.7706,  0.0563,  2.5474],
        [-0.1303,  1.1411, -0.0719, -0.9253],
        [-0.7885, -0.6436, -1.3401,  0.2429]])
tensor([ 0.1579, -0.0260, -0.9140,  0.2181, -0.6974, -0.7706,  0.0563,  2.5474,
        -0.1303,  1.1411, -0.0719, -0.9253, -0.7885, -0.6436, -1.3401,  0.2429])
tensor([[ 0.1579, -0.0260, -0.9140,  0.2181, -0.6974, -0.7706,  0.0563,  2.5474],
        [-0.1303,  1.1411, -0.0719, -0.9253, -0.7885, -0.6436, -1.3401,  0.2429]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [22]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2589])
0.2588639557361603


In [23]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [24]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [25]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [26]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))
    